import { Theme } from "../markdown";

export const minimalTheme: Theme = {
  base: {
    "--md-primary-color": `#2563eb`,
    "text-align": `left`,
    "line-height": `1.8`,
    "font-family": `'Inter', -apple-system, BlinkMacSystemFont, sans-serif`,
  },
  block: {
    container: {
      "max-width": `700px`,
      margin: `0 auto`,
      padding: `2rem`,
    },
    h1: {
      "font-size": `2.5rem`,
      "font-weight": `700`,
      "letter-spacing": `-0.025em`,
      margin: `0 0 2rem 0`,
      color: `#111827`,
    },
    h2: {
      "font-size": `2rem`,
      "font-weight": `600`,
      margin: `3rem 0 1.5rem 0`,
      color: `#374151`,
    },
    h3: {
      "font-size": `1.5rem`,
      "font-weight": `600`,
      margin: `2.5rem 0 1rem 0`,
      color: `#4b5563`,
    },
    h4: {
      "font-size": `1.25rem`,
      "font-weight": `600`,
      margin: `2rem 0 1rem 0`,
      color: `#6b7280`,
    },
    h5: {
      "font-size": `1.125rem`,
      "font-weight": `600`,
      margin: `1.5rem 0 0.5rem 0`,
      color: `#6b7280`,
    },
    h6: {
      "font-size": `1rem`,
      "font-weight": `600`,
      margin: `1.5rem 0 0.5rem 0`,
      color: `#9ca3af`,
    },
    p: {
      margin: `0 0 1.5rem 0`,
      color: `#374151`,
      "font-size": `1.125rem`,
    },
    blockquote: {
      padding: `1.5rem`,
      margin: `2rem 0`,
      "border-left": `4px solid var(--md-primary-color)`,
      background: `#f8fafc`,
      "border-radius": `0 8px 8px 0`,
    },
    blockquote_p: {
      color: `#64748b`,
      "font-style": `italic`,
      margin: `0`,
    },
    blockquote_note: {},
    blockquote_tip: {},
    blockquote_info: {},
    blockquote_important: {},
    blockquote_warning: {},
    blockquote_caution: {},
    blockquote_title: {},
    blockquote_title_note: {},
    blockquote_title_tip: {},
    blockquote_title_info: {},
    blockquote_title_important: {},
    blockquote_title_warning: {},
    blockquote_title_caution: {},
    blockquote_p_note: {},
    blockquote_p_tip: {},
    blockquote_p_info: {},
    blockquote_p_important: {},
    blockquote_p_warning: {},
    blockquote_p_caution: {},
    code_pre: {
      padding: `1.5rem`,
      "font-size": `0.9rem`,
      "line-height": `1.6`,
      background: `#1f2937`,
      color: `#f9fafb`,
      "border-radius": `12px`,
      "overflow-x": `auto`,
      margin: `2rem 0`,
    },
    code: {
      padding: `0.25rem 0.5rem`,
      "font-size": `0.9rem`,
      background: `#e5e7eb`,
      color: `#1f2937`,
      "border-radius": `6px`,
      "font-family": `'JetBrains Mono', Consolas, monospace`,
    },
    image: {
      "max-width": `100%`,
      "border-radius": `12px`,
      "box-shadow": `0 4px 6px -1px rgba(0, 0, 0, 0.1)`,
    },
    ol: {
      "padding-left": `1.5rem`,
      margin: `0 0 1.5rem 0`,
    },
    ul: {
      "padding-left": `1.5rem`,
      margin: `0 0 1.5rem 0`,
    },
    footnotes: {
      margin: `0`,
      padding: `0`,
    },
    figure: {
      margin: `0`,
      padding: `0`,
    },
    hr: {
      border: `1px solid #e5e7eb`,
      margin: `2rem 0`,
    },
    block_katex: {
      margin: `2rem 0`,
      padding: `0`,
    },
  },
  inline: {
    listitem: {
      margin: `0.5rem 0`,
      "line-height": `1.7`,
    },
    codespan: {
      padding: `0.25rem 0.5rem`,
      "font-size": `0.9rem`,
      background: `#e5e7eb`,
      color: `#1f2937`,
      "border-radius": `6px`,
      "font-family": `'JetBrains Mono', Consolas, monospace`,
    },
    link: {
      color: `var(--md-primary-color)`,
      "text-decoration": `none`,
      "border-bottom": `1px solid transparent`,
      transition: `border-color 0.2s ease`,
    },
    wx_link: {
      color: `var(--md-primary-color)`,
      "text-decoration": `none`,
    },
    strong: {
      "font-weight": `700`,
      color: `#111827`,
    },
    table: {
      "border-collapse": `collapse`,
      width: `100%`,
      margin: `2rem 0`,
      "border-radius": `8px`,
      overflow: `hidden`,
      "box-shadow": `0 1px 3px 0 rgba(0, 0, 0, 0.1)`,
    },
    thead: {
      background: `#f3f4f6`,
    },
    td: {
      padding: `12px 16px`,
      border: `1px solid #e5e7eb`,
    },
    footnote: {
      "font-size": `0.875rem`,
      color: `#6b7280`,
    },
    figcaption: {
      "text-align": `center`,
      color: `#6b7280`,
      "font-size": `0.875rem`,
      "margin-top": `0.5rem`,
    },
    em: {
      "font-style": `italic`,
    },
    inline_katex: {
      display: `inline-flex`,
      "max-width": `100%`,
      "overflow-x": `auto`,
      "vertical-align": `middle`,
    },
  },
};
