import { Theme } from "../markdown";

export const techTheme: Theme = {
  base: {
    "--md-primary-color": `#0f172a`,
    "text-align": `left`,
    "line-height": `1.7`,
    "font-family": `'SF Pro Display', -apple-system, BlinkMacSystemFont, sans-serif`,
  },
  block: {
    container: {
      "max-width": `900px`,
      margin: `0 auto`,
      padding: `2rem`,
    },
    h1: {
      "font-size": `2.25rem`,
      "font-weight": `800`,
      margin: `0 0 2rem 0`,
      color: `#0f172a`,
      background: `linear-gradient(135deg, #667eea 0%, #764ba2 100%)`,
      "-webkit-background-clip": `text`,
      "-webkit-text-fill-color": `transparent`,
    },
    h2: {
      "font-size": `1.75rem`,
      "font-weight": `700`,
      margin: `3rem 0 1.5rem 0`,
      color: `#1e293b`,
      "padding-left": `1rem`,
      "border-left": `4px solid #3b82f6`,
    },
    h3: {
      "font-size": `1.375rem`,
      "font-weight": `600`,
      margin: `2.5rem 0 1rem 0`,
      color: `#334155`,
    },
    h4: {
      "font-size": `1.125rem`,
      "font-weight": `600`,
      margin: `2rem 0 0.75rem 0`,
      color: `#475569`,
    },
    h5: {
      "font-size": `1rem`,
      "font-weight": `600`,
      margin: `1.5rem 0 0.5rem 0`,
      color: `#64748b`,
    },
    h6: {
      "font-size": `0.875rem`,
      "font-weight": `600`,
      margin: `1.5rem 0 0.5rem 0`,
      color: `#94a3b8`,
      "text-transform": `uppercase`,
      "letter-spacing": `0.05em`,
    },
    p: {
      margin: `0 0 1.5rem 0`,
      color: `#334155`,
      "font-size": `1rem`,
    },
    blockquote: {
      padding: `1.5rem`,
      margin: `2rem 0`,
      "border-left": `4px solid #f59e0b`,
      background: `#fffbeb`,
      "border-radius": `0 8px 8px 0`,
    },
    blockquote_p: {
      color: `#92400e`,
      margin: `0`,
    },
    blockquote_note: {
      "border-left-color": `#3b82f6`,
      background: `#eff6ff`,
    },
    blockquote_tip: {
      "border-left-color": `#10b981`,
      background: `#ecfdf5`,
    },
    blockquote_info: {
      "border-left-color": `#06b6d4`,
      background: `#ecfeff`,
    },
    blockquote_important: {},
    blockquote_warning: {
      "border-left-color": `#f59e0b`,
      background: `#fffbeb`,
    },
    blockquote_caution: {},
    blockquote_title: {},
    blockquote_title_note: {},
    blockquote_title_tip: {},
    blockquote_title_info: {},
    blockquote_title_important: {},
    blockquote_title_warning: {},
    blockquote_title_caution: {},
    blockquote_p_note: {},
    blockquote_p_tip: {},
    blockquote_p_info: {},
    blockquote_p_important: {},
    blockquote_p_warning: {},
    blockquote_p_caution: {},
    code_pre: {
      padding: `1.5rem`,
      "font-size": `0.875rem`,
      "line-height": `1.6`,
      background: `#0f172a`,
      color: `#e2e8f0`,
      "border-radius": `12px`,
      "overflow-x": `auto`,
      margin: `2rem 0`,
      "box-shadow": `0 10px 15px -3px rgba(0, 0, 0, 0.1)`,
    },
    code: {
      padding: `0.25rem 0.5rem`,
      "font-size": `0.875rem`,
      background: `#f1f5f9`,
      color: `#0f172a`,
      "border-radius": `6px`,
      "font-family": `'JetBrains Mono', 'Fira Code', Consolas, monospace`,
      border: `1px solid #e2e8f0`,
    },
    image: {
      "max-width": `100%`,
      "border-radius": `12px`,
      "box-shadow": `0 20px 25px -5px rgba(0, 0, 0, 0.1)`,
      margin: `2rem 0`,
    },
    ol: {
      "padding-left": `1.5rem`,
      margin: `0 0 1.5rem 0`,
    },
    ul: {
      "padding-left": `1.5rem`,
      margin: `0 0 1.5rem 0`,
    },
    footnotes: {
      margin: `0`,
      padding: `0`,
    },
    figure: {
      margin: `0`,
      padding: `0`,
    },
    hr: {
      border: `1px solid #e2e8f0`,
      margin: `2rem 0`,
    },
    block_katex: {
      margin: `2rem 0`,
      padding: `0`,
    },
  },
  inline: {
    listitem: {
      margin: `0.5rem 0`,
      "line-height": `1.6`,
    },
    codespan: {
      padding: `0.25rem 0.5rem`,
      "font-size": `0.875rem`,
      background: `#f1f5f9`,
      color: `#0f172a`,
      "border-radius": `6px`,
      "font-family": `'JetBrains Mono', 'Fira Code', Consolas, monospace`,
      border: `1px solid #e2e8f0`,
    },
    link: {
      color: `#3b82f6`,
      "text-decoration": `none`,
      "font-weight": `500`,
    },
    wx_link: {
      color: `#3b82f6`,
      "text-decoration": `none`,
    },
    strong: {
      "font-weight": `700`,
      color: `#0f172a`,
    },
    table: {
      "border-collapse": `collapse`,
      width: `100%`,
      margin: `2rem 0`,
      "border-radius": `8px`,
      overflow: `hidden`,
      "box-shadow": `0 4px 6px -1px rgba(0, 0, 0, 0.1)`,
    },
    thead: {
      background: `#f8fafc`,
      "font-weight": `600`,
    },
    td: {
      padding: `12px 16px`,
      border: `1px solid #e2e8f0`,
    },
    footnote: {
      "font-size": `0.875rem`,
      color: `#64748b`,
    },
    figcaption: {
      "text-align": `center`,
      color: `#64748b`,
      "font-size": `0.875rem`,
      "margin-top": `0.5rem`,
      "font-weight": `500`,
    },
    em: {
      "font-style": `italic`,
    },
    inline_katex: {
      display: `inline-flex`,
      "max-width": `100%`,
      "overflow-x": `auto`,
      "vertical-align": `middle`,
    },
  },
};
